### ISSUE TITLE
Component crashes on iOS - nativeView.padding not initialized

### ISSUE THREAD

**Issue by jyl087** [nstudio/nativescript-ui-kit#1]
On iOS, the marquee component crashes with the error: 

_"Cannot ready property 'right' of undefined at [paddingTop:setNative](file:**` .... nativescript/core/ui/label/index.ios.js:..._

I fixed it by modifying the file: @nstudio/nativescript-label-marquee/index.ios.js

in function `initNativeView()`, I added the line:

    nativeView.padding = {top:0, right:0, bottom:0, left:0};

**Comment by NathanWalker** [comment]
@jyl087 We can add that into `initNativeView` but would be curious the context usage. Would it be possible to share a repo with the component added which showed this issue? I haven't seen that issue with plain/core or Angular but perhaps a different framework exhibits that?

**Comment by NathanWalker** [comment]
Fixed in 1.0.1 - the issue arises out of an edge case in @nativescript/core actually and we'll plan to add some other things to {N} 8.2 which will ultimately fix deeper cases around this.

@jyl087 let us know if further issue and if can confirm 1.0.1 fixes it for you now would be great, thanks for reporting.

**Comment by jyl087** [comment]
Great! Glad to be of help.
